name: nigms_sandbox_ud__submodule_5
channels:
  - conda-forge
  - defaults
dependencies:
  - deepchem=2.8
  - ipykernel
  - jupyter
  - keras=2.15.0
  - numpy
  - python=3.9
  - rdkit
  - scikit-learn=1.6
  - scipy=1.9
  - seaborn
  - tensorflow
