name: nigms_sandbox_ud
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.9
  - requests # Will be removed
  - scikit-learn
  - scipy
  - seaborn
  - pip:
      - jupyterquiz
