name: nigms_sandbox_ud__submodule_5
channels:
  - conda-forge
  - defaults
dependencies:
  - deepchem
  - ipykernel
  - jupyter
  - keras=2.15.0
  - python=3.9
  - rdkit
  - scipy=1.7.3
  - seaborn
  - tensorflow
