name: nigms_sandbox_ud
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - python=3.9
  - requests # this will need to be removed
  - scikit-learn
  - scipy
  - seaborn
