name: nigms_sandbox_ud
dependencies:
  - deepchem
  - ipykernel
  - joblib
  - jupyter
  - keras
  - matplotlib=3.3.4
  - mordredcommunity
  - numpy
  - openpyxl
  - pandas
  - py3dmol
  - rdkit
  - scikit-learn
  - seaborn
  - skater
  - tables
  - tensorflow
